spring.application.name=todo
spring.datasource.url=jdbc:sqlite:todo.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# secret key (can generate at https://jwtsecretkeygenerator.com/)
security.jwt.secret-key=57oa74mYuR4cMrcj5YKgxG7k345rYpwZxe8ihoba3Wj
# expiration time (1 hr in milliseconds)
security.jwt.expiration-time=3600000